name: Azure Deploy
on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch: 
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
      - uses: actions/checkout@v6
      - uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
  
  

  
